/**
 * Seed agents.health_knowledge with proper embeddings.
 *
 * Generates embeddings via OpenRouter perplexity/pplx-embed-v1-4b (2560 dims),
 * writes them to a SQL file, then applies via supabase CLI — bypassing PostgREST
 * so the agents schema does not need to be separately exposed.
 *
 * Run: npx tsx --env-file=.env scripts/seed-health-knowledge.ts
 */

import { execSync } from 'child_process';
import { writeFileSync, unlinkSync } from 'fs';
import { join } from 'path';

const OPENROUTER_API_KEY = process.env.OPENROUTER_API_KEY!;

if (!OPENROUTER_API_KEY) {
  console.error('OPENROUTER_API_KEY is required. Run with --env-file=.env');
  process.exit(1);
}

// ---------------------------------------------------------------------------
// 65 clinical knowledge chunks — exact content from migration 0024
// ---------------------------------------------------------------------------

type KnowledgeRow = { content: string; category: string; source: string; evidence_level: string };

const RECORDS: KnowledgeRow[] = [
  // CV (10)
  { category: 'cv', evidence_level: 'I', source: '2023 Australian CVD Risk Guideline. Heart Foundation / RACGP / MJA 2024', content: 'The 2023 Australian CVD Risk Guideline (Heart Foundation/RACGP) uses the AusCVD Risk Calculator to estimate 5-year absolute cardiovascular disease risk. Low risk is defined as < 5%, intermediate as 5–< 10%, and high risk as ≥ 10%. People at high risk should initiate both blood pressure–lowering and lipid-modifying pharmacotherapy. Reassessment is recommended within 2 years for intermediate-risk patients and within 5 years for low-risk patients.' },
  { category: 'cv', evidence_level: 'I', source: '2023 Australian CVD Risk Guideline. Heart Foundation / RACGP / MJA 2024', content: 'For high CVD risk patients (≥ 10% 5-year risk), LDL cholesterol targets are < 1.8 mmol/L and non-HDL < 2.6 mmol/L. For very high risk (known ASCVD), LDL target is < 1.4 mmol/L. Statin therapy is first-line lipid-lowering treatment. Irrespective of calculated risk, total cholesterol > 7.5 mmol/L or blood pressure > 160/100 mmHg warrants pharmacotherapy.' },
  { category: 'cv', evidence_level: 'I', source: '2023 Australian CVD Risk Guideline. Heart Foundation / RACGP / MJA 2024', content: 'Blood pressure targets in the 2023 Australian CVD Risk Guideline: general population target < 140/90 mmHg; for high CVD risk and diabetes < 130/80 mmHg. A 10 mmHg reduction in systolic BP reduces stroke risk by approximately 27% and coronary heart disease by 20%. First-line antihypertensives include ACE inhibitors, ARBs, calcium channel blockers, and thiazide diuretics.' },
  { category: 'cv', evidence_level: 'I', source: '2023 Australian CVD Risk Guideline. Heart Foundation / RACGP / MJA 2024', content: 'Smoking is the single most modifiable cardiovascular risk factor. Cigarette smoking doubles the risk of coronary heart disease. Within 1 year of smoking cessation, excess coronary artery disease risk is halved. Within 5–15 years, CVD risk approaches that of a lifetime non-smoker. Smoking cessation programs (NRT + behavioural support) should be offered to all current smokers.' },
  { category: 'cv', evidence_level: 'I', source: '2023 Australian CVD Risk Guideline. Heart Foundation / RACGP / MJA 2024', content: 'HDL cholesterol has an inverse relationship with cardiovascular risk. HDL < 1.0 mmol/L in men and < 1.2 mmol/L in women is a risk factor in the 2023 Australian CVD Risk Guideline. LDL drives atherosclerotic plaque formation through oxidised LDL incorporation into macrophage foam cells. Each 1 mmol/L reduction in LDL is associated with approximately 22% reduction in major cardiovascular events.' },
  { category: 'cv', evidence_level: 'I', source: '2023 Australian CVD Risk Guideline. Heart Foundation / RACGP / MJA 2024', content: 'High-sensitivity C-reactive protein (hs-CRP) is an independent predictor of cardiovascular risk. hs-CRP > 3 mg/L in the absence of infection or systemic inflammation indicates significantly elevated cardiovascular risk and may reclassify intermediate-risk patients to high risk. hs-CRP is not incorporated into the AusCVD Risk Calculator but can inform clinical decision-making. Source: ACC/AHA 2019 Primary Prevention Guidelines.' },
  { category: 'cv', evidence_level: 'I', source: '2023 Australian CVD Risk Guideline. Heart Foundation / RACGP / MJA 2024', content: 'Homocysteine elevation (> 15 µmol/L) is associated with a 2-fold increased risk of cardiovascular disease through endothelial injury and thrombosis mechanisms. B vitamins (B6, B12, folate) reduce homocysteine levels but RCT evidence for CVD event reduction is mixed. Homocysteine levels > 20 µmol/L warrant investigation and B vitamin supplementation. Source: Cochrane systematic review.' },
  { category: 'cv', evidence_level: 'I', source: '2023 Australian CVD Risk Guideline. Heart Foundation / RACGP / MJA 2024', content: 'Lipoprotein(a) [Lp(a)] is a genetically determined, independent risk factor for atherosclerotic cardiovascular disease. Elevated Lp(a) > 75 nmol/L doubles ASCVD risk. Unlike LDL, Lp(a) is not substantially reduced by statins. It should be measured once in all adults, particularly those with family history of premature CVD or statin-treated patients not achieving LDL targets. Source: ACC/AHA 2019.' },
  { category: 'cv', evidence_level: 'I', source: '2023 Australian CVD Risk Guideline. Heart Foundation / RACGP / MJA 2024', content: 'Atrial fibrillation (AF) independently increases stroke risk 5-fold. The CHA2DS2-VASc score is used to determine anticoagulation therapy: score ≥ 2 in males or ≥ 3 in females warrants anticoagulation. Undetected AF affects ~1–2% of Australians. Pulse palpation and ECG screening for AF is recommended in all adults > 65 years. Source: National Heart Foundation of Australia 2018.' },
  { category: 'cv', evidence_level: 'I', source: '2023 Australian CVD Risk Guideline. Heart Foundation / RACGP / MJA 2024', content: 'Marine omega-3 fatty acids (EPA+DHA) reduce triglycerides by 25–30% at 2–4 g/day. The REDUCE-IT trial (NEJM 2019) demonstrated that high-dose icosapentaenoic acid (EPA, 4 g/day as Vascepa) reduced major adverse cardiovascular events by 25% in statin-treated patients with elevated triglycerides. Standard fish oil (EPA+DHA combination) at 1–2 g/day provides general cardiovascular support.' },

  // METABOLIC (10)
  { category: 'metabolic', evidence_level: 'I', source: 'AUSDRISK/Australian Dept of Health; WHO 2011 Diabetes Criteria; Diabetes Prevention Program Trial', content: 'The AUSDRISK tool (Australian Type 2 Diabetes Risk Assessment) assigns 5-year T2DM probability based on: age, sex, ethnicity, waist circumference, physical activity, family history of diabetes, history of high blood glucose, and antihypertensive medication use. Scores: ≤ 5 = low risk (1/100); 6–8 = 1/50; 9–11 = 1/30; 12–15 = 1/14 (high risk, MBS Item 713 eligible); ≥ 16 = very high risk.' },
  { category: 'metabolic', evidence_level: 'I', source: 'AUSDRISK/Australian Dept of Health; WHO 2011 Diabetes Criteria; Diabetes Prevention Program Trial', content: 'WHO 2011 diagnostic criteria for type 2 diabetes: HbA1c ≥ 53 mmol/mol (7.0%) on two occasions; fasting plasma glucose ≥ 7.0 mmol/L; or 2-hour glucose ≥ 11.1 mmol/L on 75g OGTT. Impaired fasting glucose (IFG): fasting glucose 6.1–6.9 mmol/L. Impaired glucose tolerance (IGT): 2-hour glucose 7.8–11.0 mmol/L. HbA1c 48–52 mmol/mol represents borderline/pre-diabetes range in some Australian guidelines.' },
  { category: 'metabolic', evidence_level: 'I', source: 'AUSDRISK/Australian Dept of Health; WHO 2011 Diabetes Criteria; Diabetes Prevention Program Trial', content: 'HOMA-IR (Homeostatic Model Assessment of Insulin Resistance) = (fasting insulin mIU/L × fasting glucose mmol/L) ÷ 22.5. HOMA-IR > 2.9 indicates insulin resistance; > 5.0 indicates significant insulin resistance. Elevated HOMA-IR predates T2DM onset by years and is associated with metabolic syndrome, MASLD (metabolic-associated steatotic liver disease), and elevated cardiovascular risk.' },
  { category: 'metabolic', evidence_level: 'I', source: 'AUSDRISK/Australian Dept of Health; WHO 2011 Diabetes Criteria; Diabetes Prevention Program Trial', content: 'Metabolic syndrome (IDF/AHA/NHLBI consensus) requires central obesity (waist ≥ 94 cm male / ≥ 80 cm female for Europeans; lower thresholds for Asian populations) PLUS two of: triglycerides ≥ 1.7 mmol/L; HDL < 1.0 mmol/L male / < 1.3 mmol/L female; SBP ≥ 130 or DBP ≥ 85 mmHg or on antihypertensives; fasting glucose ≥ 5.6 mmol/L or on anti-diabetic therapy.' },
  { category: 'metabolic', evidence_level: 'I', source: 'AUSDRISK/Australian Dept of Health; WHO 2011 Diabetes Criteria; Diabetes Prevention Program Trial', content: 'The Diabetes Prevention Program (DPP, NEJM 2002) demonstrated that intensive lifestyle intervention (7% weight loss + 150 min/week moderate physical activity) reduced incidence of T2DM by 58% over 3 years compared to placebo in individuals with impaired glucose tolerance. Metformin reduced incidence by 31%. Lifestyle intervention was more effective than metformin in older participants (≥ 60 years).' },
  { category: 'metabolic', evidence_level: 'I', source: 'AUSDRISK/Australian Dept of Health; WHO 2011 Diabetes Criteria; Diabetes Prevention Program Trial', content: 'Fasting plasma glucose measures hepatic insulin sensitivity; 2-hour post-load glucose measures peripheral glucose disposal. Both are independent predictors of T2DM and cardiovascular events. A 2-hour glucose 7.8–11.0 mmol/L on OGTT (impaired glucose tolerance) carries higher cardiovascular risk than isolated impaired fasting glucose, making OGTT the more clinically informative test.' },
  { category: 'metabolic', evidence_level: 'I', source: 'AUSDRISK/Australian Dept of Health; WHO 2011 Diabetes Criteria; Diabetes Prevention Program Trial', content: 'Visceral (central) adiposity — measured by waist circumference — is a stronger predictor of metabolic risk than BMI alone. Waist circumference > 94 cm in men and > 80 cm in women (IDF European thresholds) significantly elevates risk of insulin resistance, T2DM, and CVD. Visceral fat secretes pro-inflammatory adipokines including TNF-α, IL-6, and leptin that directly impair insulin signalling.' },
  { category: 'metabolic', evidence_level: 'I', source: 'AUSDRISK/Australian Dept of Health; WHO 2011 Diabetes Criteria; Diabetes Prevention Program Trial', content: 'Sleep deprivation (< 6 hours/night) is independently associated with impaired glucose metabolism. Short sleep increases cortisol and ghrelin, decreases leptin, and promotes insulin resistance. Studies show a 28% higher risk of T2DM in individuals sleeping < 6 hours vs 7–8 hours. Sleep optimisation is a modifiable metabolic intervention. Source: Cappuccio et al., Diabetes Care 2010.' },
  { category: 'metabolic', evidence_level: 'I', source: 'AUSDRISK/Australian Dept of Health; WHO 2011 Diabetes Criteria; Diabetes Prevention Program Trial', content: 'Alcohol consumption elevates triglycerides (increases VLDL synthesis) and contributes to fatty liver, worsening metabolic syndrome. Even moderate alcohol intake (> 2 standard drinks/day) is associated with elevated fasting glucose and reduced insulin sensitivity over time. Abstinence or minimal alcohol intake (< 7 std drinks/week) is recommended for metabolic health optimisation.' },
  { category: 'metabolic', evidence_level: 'I', source: 'AUSDRISK/Australian Dept of Health; WHO 2011 Diabetes Criteria; Diabetes Prevention Program Trial', content: 'Elevated serum uric acid (hyperuricaemia: > 420 µmol/L male / > 360 µmol/L female) is associated with gout, chronic kidney disease, and metabolic syndrome. Uric acid inhibits insulin signalling and is an independent predictor of T2DM onset. Fructose consumption (high-fructose corn syrup, soft drinks) is the primary dietary driver of elevated uric acid. Reducing fructose intake lowers uric acid by 10–15%.' },

  // NEURO (10)
  { category: 'neuro', evidence_level: 'I', source: '2024 Lancet Commission on Dementia Prevention. Livingston et al. Lancet 2024', content: 'The 2024 Lancet Commission on Dementia Prevention identified 14 modifiable risk factors that together account for approximately 45% of global dementia cases (population attributable risk). The two new factors identified in 2024 (added to the original 12 from 2020) are vision loss and high LDL cholesterol. Addressing all 14 factors could theoretically prevent or delay up to 45% of dementia cases worldwide.' },
  { category: 'neuro', evidence_level: 'I', source: '2024 Lancet Commission on Dementia Prevention. Livingston et al. Lancet 2024', content: 'Hearing loss is the largest single modifiable dementia risk factor in midlife, accounting for 8.2% of population attributable risk (PAR) in the 2024 Lancet Commission. Untreated hearing loss is associated with social withdrawal, reduced cognitive stimulation, and accelerated cognitive decline. Hearing aid use in people with moderate hearing loss reduces the rate of cognitive decline by approximately 50% (ACHIEVE trial, Lancet 2023).' },
  { category: 'neuro', evidence_level: 'I', source: '2024 Lancet Commission on Dementia Prevention. Livingston et al. Lancet 2024', content: 'Hypertension in midlife (ages 40–65) independently doubles the risk of dementia later in life. Treating hypertension to < 130/80 mmHg in midlife is one of the most evidence-based dementia prevention strategies. The SPRINT-MIND trial demonstrated that intensive blood pressure lowering (SBP target < 120 mmHg) significantly reduced mild cognitive impairment risk compared to standard control (< 140 mmHg).' },
  { category: 'neuro', evidence_level: 'I', source: '2024 Lancet Commission on Dementia Prevention. Livingston et al. Lancet 2024', content: 'Physical inactivity is a modifiable dementia risk factor, accounting for ~2% PAR in the Lancet Commission 2024. Regular aerobic exercise (≥ 150 minutes/week of moderate-intensity) increases BDNF (brain-derived neurotrophic factor), promotes neurogenesis in the hippocampus, and improves cerebrovascular perfusion. Exercise is associated with 35% lower risk of cognitive decline in observational studies.' },
  { category: 'neuro', evidence_level: 'I', source: '2024 Lancet Commission on Dementia Prevention. Livingston et al. Lancet 2024', content: 'Depression is both a risk factor and an early symptom of dementia — the causal relationship is bidirectional. Depression in midlife increases dementia risk by approximately 65%. Mechanisms include HPA axis dysregulation, elevated cortisol causing hippocampal atrophy, and neuroinflammation. Treating depression with antidepressants and psychotherapy is essential for both mental health and dementia prevention.' },
  { category: 'neuro', evidence_level: 'I', source: '2024 Lancet Commission on Dementia Prevention. Livingston et al. Lancet 2024', content: 'Sleep quality has a direct impact on amyloid-beta clearance from the brain via the glymphatic system. The glymphatic system is most active during slow-wave sleep, clearing amyloid and tau proteins that accumulate during waking hours. Chronic sleep < 6 hours or > 9 hours is associated with higher amyloid burden on PET imaging and increased dementia risk. Sleep optimisation is a cost-free dementia prevention strategy.' },
  { category: 'neuro', evidence_level: 'I', source: '2024 Lancet Commission on Dementia Prevention. Livingston et al. Lancet 2024', content: 'Social isolation in late life (age 65+) accounts for ~5% population attributable risk for dementia (Lancet Commission 2024). Loneliness and social isolation cause chronic psychological stress, HPA axis activation, and pro-inflammatory cytokine production. Strong social networks, community participation, and regular social engagement are protective against cognitive decline.' },
  { category: 'neuro', evidence_level: 'I', source: '2024 Lancet Commission on Dementia Prevention. Livingston et al. Lancet 2024', content: "The MIND diet (Mediterranean-DASH Intervention for Neurodegenerative Delay) combines elements of the Mediterranean and DASH diets with specific emphasis on brain-healthy foods: berries (2+ servings/week), leafy greens (1+ serving/day), fish (1+ meal/week), nuts (5+ servings/week), olive oil as primary fat. The MIND diet was associated with slower cognitive decline and 53% lower risk of Alzheimer's disease in the original MIND trial." },
  { category: 'neuro', evidence_level: 'I', source: '2024 Lancet Commission on Dementia Prevention. Livingston et al. Lancet 2024', content: "Traumatic brain injury (TBI) is associated with increased long-term risk of dementia, particularly Alzheimer's disease and chronic traumatic encephalopathy (CTE). Even mild TBI (concussion) with loss of consciousness doubles dementia risk in long-term follow-up. Multiple mild TBIs (as in contact sports) have a synergistic effect. Helmets and fall prevention are primary prevention strategies." },
  { category: 'neuro', evidence_level: 'I', source: '2024 Lancet Commission on Dementia Prevention. Livingston et al. Lancet 2024', content: 'High LDL cholesterol (> 3.0 mmol/L) in midlife is a newly identified modifiable dementia risk factor in the 2024 Lancet Commission. Elevated LDL promotes cerebral small vessel disease, vascular dementia, and potentially amyloid-beta production. Statin therapy for LDL reduction in midlife may reduce vascular dementia risk. LDL control is now part of comprehensive dementia prevention alongside cardiovascular prevention.' },

  // ONCO (10)
  { category: 'onco', evidence_level: 'I', source: 'WHO/IARC World Cancer Report 2024; Cancer Council Australia; WHO 2026 cancer prevention report', content: 'WHO and IARC analysis published in 2026 found that approximately 40% of cancer cases globally could be prevented by addressing modifiable risk factors. In 2022, an estimated 7.1 million (37%) of 19.3 million new cancer cases were attributable to 30 preventable causes including tobacco, alcohol, obesity, physical inactivity, UV radiation, and nine cancer-causing infections.' },
  { category: 'onco', evidence_level: 'I', source: 'WHO/IARC World Cancer Report 2024; Cancer Council Australia; WHO 2026 cancer prevention report', content: 'Tobacco is the leading preventable cause of cancer globally, responsible for approximately 15% of all new cancer cases (IARC 2024). Smoking causes cancers of the lung, mouth, throat, oesophagus, stomach, pancreas, kidney, bladder, cervix, and bone marrow (AML). Risk of lung cancer begins declining within 5 years of smoking cessation. After 10 years of cessation, lung cancer risk is halved compared to continuing smokers.' },
  { category: 'onco', evidence_level: 'I', source: 'WHO/IARC World Cancer Report 2024; Cancer Council Australia; WHO 2026 cancer prevention report', content: 'Excess body weight (overweight BMI 25–29.9 and obese BMI ≥ 30) is linked to 13 cancer types by IARC: breast (post-menopausal), colorectal, endometrial, oesophageal (adenocarcinoma), gallbladder, kidney, liver, ovarian, pancreatic, stomach (cardia), thyroid, multiple myeloma, and meningioma. Mechanisms include elevated oestrogen, insulin, IGF-1, and chronic inflammation. Achieving and maintaining healthy BMI 18.5–24.9 significantly reduces cancer risk.' },
  { category: 'onco', evidence_level: 'I', source: 'WHO/IARC World Cancer Report 2024; Cancer Council Australia; WHO 2026 cancer prevention report', content: 'There is no safe level of alcohol consumption for cancer risk (WHO 2023 position statement). Alcohol is causally linked to cancers of the mouth, pharynx, larynx, oesophagus, liver, colorectum, and female breast. Even 1 standard drink per day is associated with increased breast cancer risk (10–15% relative risk increase per 10 g alcohol/day). Risk increases linearly with consumption.' },
  { category: 'onco', evidence_level: 'I', source: 'WHO/IARC World Cancer Report 2024; Cancer Council Australia; WHO 2026 cancer prevention report', content: 'Physical inactivity is associated with increased risk of colon cancer (40–50% risk reduction with regular activity), breast cancer (20–30% reduction), and endometrial cancer (30–40% reduction). The Cancer Council Australia recommends ≥ 150 minutes of moderate-intensity physical activity per week for cancer risk reduction. Exercise reduces cancer risk through multiple mechanisms including insulin/IGF-1 regulation, immune function, prostaglandin levels, and reduced obesity.' },
  { category: 'onco', evidence_level: 'I', source: 'WHO/IARC World Cancer Report 2024; Cancer Council Australia; WHO 2026 cancer prevention report', content: 'UV radiation is the primary cause of all skin cancers (basal cell carcinoma, squamous cell carcinoma, and melanoma) in Australia. Australia has the highest melanoma incidence globally. SunSmart guidelines recommend: SPF 50+ sunscreen applied 20 minutes before sun exposure and reapplied every 2 hours; protective clothing, hats, and sunglasses; seeking shade between 10am–3pm (AEDT). Regular full-skin checks by a doctor are recommended annually for high-risk individuals.' },
  { category: 'onco', evidence_level: 'I', source: 'WHO/IARC World Cancer Report 2024; Cancer Council Australia; WHO 2026 cancer prevention report', content: "The National Bowel Cancer Screening Program (NBCSP) offers free immunochemical faecal occult blood test (iFOBT) kits to all Australians aged 50–74 years every 2 years. Bowel cancer is Australia's second most common cancer. When detected early (Stage I), the 5-year survival rate is > 90%. Regular iFOBT screening reduces bowel cancer mortality by approximately 25%. A positive iFOBT requires colonoscopy follow-up." },
  { category: 'onco', evidence_level: 'I', source: 'WHO/IARC World Cancer Report 2024; Cancer Council Australia; WHO 2026 cancer prevention report', content: 'BreastScreen Australia provides free mammograms every 2 years to women aged 50–74 years. Women aged 40–49 and 75+ can self-refer. Regular mammographic screening reduces breast cancer mortality by approximately 20% in screened women. Women with BRCA1/2 mutations or strong family history (two 1st-degree relatives with breast/ovarian cancer) are eligible for enhanced surveillance including MRI.' },
  { category: 'onco', evidence_level: 'I', source: 'WHO/IARC World Cancer Report 2024; Cancer Council Australia; WHO 2026 cancer prevention report', content: 'The National Cervical Screening Program (NCSP) replaced the Pap smear in 2017 with a 5-yearly Cervical Screening Test (CST) using HPV DNA testing for women aged 25–74. HPV vaccination (Gardasil 9) has dramatically reduced high-risk HPV prevalence in Australian youth. 99% of cervical cancers are caused by HPV. Regular CST reduces cervical cancer mortality. HPV vaccination does not eliminate the need for continued cervical screening.' },
  { category: 'onco', evidence_level: 'I', source: 'WHO/IARC World Cancer Report 2024; Cancer Council Australia; WHO 2026 cancer prevention report', content: 'Processed meat (bacon, ham, sausages, hot dogs, and deli meats) is classified as a Group 1 carcinogen by IARC — the highest classification, meaning there is sufficient evidence of cancer causation in humans. Each 50 g serving of processed meat per day increases colorectal cancer risk by approximately 18%. Red unprocessed meat is classified IARC Group 2A (probably carcinogenic). Cancer Council Australia recommends limiting red meat to < 500 g/week and minimising processed meat.' },

  // MSK (10)
  { category: 'msk', evidence_level: 'I', source: '2024 RACGP / Healthy Bones Australia Osteoporosis Guideline. MJA 2025; WHO FRAX', content: 'The 2024 RACGP and Healthy Bones Australia guideline uses FRAX (WHO Fracture Risk Assessment Tool) to estimate 10-year major osteoporotic fracture (MOF) risk. Thresholds: FRAX MOF ≥ 10% → refer for DXA bone mineral density scan; FRAX MOF ≥ 20% and/or hip fracture ≥ 3% → consider pharmacotherapy; FRAX MOF ≥ 30% or hip ≥ 4.5% → very high/imminent fracture risk → treat urgently. FRAX tool: fraxplus.org.' },
  { category: 'msk', evidence_level: 'I', source: '2024 RACGP / Healthy Bones Australia Osteoporosis Guideline. MJA 2025; WHO FRAX', content: 'Key osteoporosis risk factors assessed in FRAX and RACGP 2024 guideline: age (risk doubles every decade after 50), female sex, low BMI (< 19 kg/m²), prior fragility fracture (most important predictor of future fracture), parental hip fracture, corticosteroid use (≥ 5 mg prednisolone equivalent/day for ≥ 3 months), rheumatoid arthritis, secondary osteoporosis (coeliac disease, IBD, hypogonadism, chronic liver disease), alcohol ≥ 3 units/day, current smoking.' },
  { category: 'msk', evidence_level: 'I', source: '2024 RACGP / Healthy Bones Australia Osteoporosis Guideline. MJA 2025; WHO FRAX', content: 'Adequate calcium intake is the foundation of bone health. Recommended daily intake: 1,000 mg/day for adults; 1,300 mg/day for adults over 70 and women over 50. Diet-first approach recommended: dairy (yoghurt, cheese, milk), fortified foods, canned fish with bones, tofu. Calcium supplements should only be used when diet is insufficient (< 800 mg/day from food). Calcium carbonate is best absorbed with food; calcium citrate can be taken without food.' },
  { category: 'msk', evidence_level: 'I', source: '2024 RACGP / Healthy Bones Australia Osteoporosis Guideline. MJA 2025; WHO FRAX', content: 'Vitamin D is essential for calcium absorption and bone mineralisation. Target serum 25-hydroxyvitamin D level is > 50 nmol/L (sufficient) with optimal 75–150 nmol/L. Vitamin D deficiency (< 30 nmol/L) significantly impairs calcium absorption and increases fracture risk. Standard replacement: 1,000–2,000 IU/day; medical supervision required for ≥ 3,000 IU/day. Sunlight exposure (arms and legs, 10–15 min outside peak UV) remains the most efficient source.' },
  { category: 'msk', evidence_level: 'I', source: '2024 RACGP / Healthy Bones Australia Osteoporosis Guideline. MJA 2025; WHO FRAX', content: 'Weight-bearing exercise is the most effective non-pharmacological intervention for building and maintaining bone density. High-impact loading (jogging, jumping, dancing) and resistance training improve bone mineral density in the spine and hip. RACGP 2024 recommends ≥ 2 strength training sessions/week and 150 minutes of moderate aerobic exercise/week for bone health. Balance training (tai chi, yoga) reduces falls risk by approximately 25%.' },
  { category: 'msk', evidence_level: 'I', source: '2024 RACGP / Healthy Bones Australia Osteoporosis Guideline. MJA 2025; WHO FRAX', content: 'Falls prevention is critical for fracture prevention in older adults. The RACGP recommends a multifactorial falls prevention programme for individuals at elevated fracture risk including: muscle strengthening (lower limb) and balance training, home hazard assessment and modification (remove rugs, improve lighting, install grab rails), medication review (hypnotics, antihypertensives that cause orthostatic hypotension), and vision correction.' },
  { category: 'msk', evidence_level: 'I', source: '2024 RACGP / Healthy Bones Australia Osteoporosis Guideline. MJA 2025; WHO FRAX', content: 'Sarcopenia (age-related loss of muscle mass and function) accelerates after age 60, with average muscle mass loss of 1–2% per decade from age 30 and accelerating to 3–5% per decade after 60. Diagnostic criteria: low muscle mass (DXA-measured appendicular lean mass index) plus low muscle strength (grip strength < 27 kg male / < 16 kg female, dynamometer). Prevention: resistance training (2–3x/week) and adequate protein intake (1.2–1.6 g/kg/day).' },
  { category: 'msk', evidence_level: 'I', source: '2024 RACGP / Healthy Bones Australia Osteoporosis Guideline. MJA 2025; WHO FRAX', content: 'BMI > 27.5 kg/m² is associated with a 4-fold increased risk of knee osteoarthritis (OA) compared to healthy weight (AIHW data). Each 5 kg increase in body weight increases knee joint load by 20 kg during walking. Weight loss of 5–10% in overweight individuals with knee OA reduces pain by 30–50% and improves function. Exercise therapy (aquatic and land-based) is first-line treatment for knee OA regardless of radiographic severity.' },
  { category: 'msk', evidence_level: 'I', source: '2024 RACGP / Healthy Bones Australia Osteoporosis Guideline. MJA 2025; WHO FRAX', content: 'Rheumatoid arthritis (RA) is associated with systemic inflammation (elevated CRP, ESR, IL-6, TNF-α) and increased cardiovascular disease risk — 1.5–2x higher than age-matched controls. RA itself is a FRAX risk factor. Disease-modifying antirheumatic drugs (DMARDs) reduce systemic inflammation and fracture risk. Regular cardio-metabolic monitoring is recommended for RA patients.' },
  { category: 'msk', evidence_level: 'I', source: '2024 RACGP / Healthy Bones Australia Osteoporosis Guideline. MJA 2025; WHO FRAX', content: 'Glucosamine sulfate (1,500 mg/day) and chondroitin sulfate (1,200 mg/day) have Level II evidence for symptomatic relief in knee osteoarthritis, particularly in moderate-to-severe OA. The GAIT trial (NEJM 2006) showed combination therapy superior to placebo in moderate-to-severe knee OA subgroup. Australian ARTG registered. Effect size is modest; response should be assessed at 3 months. No evidence for prevention of structural progression.' },

  // SUPPLEMENTS (10)
  { category: 'supplements', evidence_level: 'I', source: 'NIH ODS; Cochrane systematic reviews; NEJM', content: 'Vitamin D status (NIH ODS): Deficiency = serum 25-OH-D < 50 nmol/L (20 ng/mL); Insufficiency = 50–75 nmol/L; Sufficiency = 75–125 nmol/L; Optimal for bone health = 75–150 nmol/L. Treatment: 1,000–2,000 IU/day cholecalciferol (D3) for insufficiency; 3,000–5,000 IU/day under medical supervision for deficiency. Upper tolerable intake level: 4,000 IU/day without medical supervision. Vitamin D3 (cholecalciferol) more potent than D2 (ergocalciferol). Recheck 25-OH-D after 3 months of supplementation.' },
  { category: 'supplements', evidence_level: 'I', source: 'NIH ODS; Cochrane systematic reviews; NEJM', content: 'Marine omega-3 fatty acids EPA+DHA: General CV support dose = 1–2 g/day EPA+DHA (Level I evidence for triglyceride reduction 25–30%). Hypertriglyceridaemia treatment = 2–4 g/day. REDUCE-IT trial (NEJM 2019, Level I): icosapentaenoic acid (EPA, 4 g/day as Vascepa/Epanova) reduced major adverse cardiovascular events by 25% in statin-treated patients with TG ≥ 1.7 mmol/L. Fish oil > 3 g/day may increase bleeding risk with anticoagulants.' },
  { category: 'supplements', evidence_level: 'II', source: 'NIH ODS; Cochrane systematic reviews; NEJM', content: 'Magnesium (NIH ODS): Recommended dietary intake (RDI) = 310–320 mg/day for adult women; 400–420 mg/day for adult men. Upper tolerable intake level for supplemental magnesium = 350 mg/day. Forms with best bioavailability: magnesium glycinate (amino acid chelate), magnesium malate, magnesium citrate. Magnesium oxide has only 4% bioavailability. Magnesium deficiency is common in type 2 diabetes, hypertension, and alcohol use disorder. Meta-analysis (2016): supplemental magnesium reduces SBP by ~2 mmHg and DBP by ~1.78 mmHg.' },
  { category: 'supplements', evidence_level: 'I', source: 'NIH ODS; Cochrane systematic reviews; NEJM', content: 'Vitamin B12 (cobalamin) — NIH ODS: Deficiency threshold = serum B12 < 148 pmol/L (200 pg/mL). Optimal = > 300 pmol/L. Functional deficiency can occur with total B12 148–220 pmol/L — check holotranscobalamin (active B12) and methylmalonic acid for confirmation. Active B12 (holotranscobalamin) < 35 pmol/L indicates functional deficiency. Treatment: methylcobalamin 1,000 mcg/day orally. Risk groups: vegans, vegetarians, elderly, long-term metformin users.' },
  { category: 'supplements', evidence_level: 'II', source: 'NIH ODS; Cochrane systematic reviews; NEJM', content: 'CoQ10 (ubiquinol) — Q-SYMBIO trial (JACC Heart Failure 2014, Level II): CoQ10 300 mg/day reduced MACE (major adverse cardiovascular events) by 43% and cardiovascular mortality by 43% vs placebo in heart failure patients over 2 years. For statin-associated myopathy: 100–200 mg/day ubiquinol has Level II evidence for symptom reduction. Note: CoQ10 may slightly reduce warfarin effect — monitor INR. Ubiquinol (reduced form) superior bioavailability vs ubiquinone in patients over 50.' },
  { category: 'supplements', evidence_level: 'I', source: 'NIH ODS; Cochrane systematic reviews; NEJM', content: 'Iron supplementation — WHO guidelines: Treat confirmed iron deficiency only (ferritin < 15 µg/L or < 30 µg/L with symptoms). Ferrous bisglycinate (chelated): 25–50 mg elemental iron, best tolerated form (superior GI profile vs ferrous sulfate). Take with 500 mg Vitamin C to enhance absorption by 2–3x. Separate from levothyroxine, quinolone antibiotics, calcium, magnesium by ≥ 2 hours. Recheck ferritin, haemoglobin after 3 months. Identify and treat underlying cause.' },
  { category: 'supplements', evidence_level: 'II', source: 'NIH ODS; Cochrane systematic reviews; NEJM', content: 'Zinc (NIH ODS): RDI 8 mg/day female; 11 mg/day male. Upper tolerable limit 40 mg/day. Zinc deficiency associated with impaired immune function, delayed wound healing, hair loss, reduced testosterone, and loss of taste/smell. Supplemental forms with best bioavailability: zinc picolinate, zinc gluconate, zinc bisglycinate. Excess zinc (> 40 mg/day) can cause copper deficiency (competes for intestinal absorption). Zinc sulfate has lower bioavailability and poorer GI tolerance.' },
  { category: 'supplements', evidence_level: 'II', source: 'NIH ODS; Cochrane systematic reviews; NEJM', content: 'Curcumin (from turmeric): Bioavailability of curcumin alone is < 1% due to poor absorption, rapid metabolism, and rapid elimination. Co-administration of piperine (5 mg, from black pepper) increases curcumin bioavailability by approximately 20-fold. Recommended dose: 500–1,000 mg curcuminoids/day with piperine. Anti-inflammatory mechanisms: inhibition of NF-κB, COX-2, and prostaglandin E2. Level II evidence for knee OA symptom relief. Mild antiplatelet activity — caution with anticoagulants.' },
  { category: 'supplements', evidence_level: 'II', source: 'NIH ODS; Cochrane systematic reviews; NEJM', content: 'Vitamin K2 (menaquinone-7, MK-7): The Rotterdam Study (2004) found the highest quartile of vitamin K2 intake associated with 57% reduction in cardiovascular mortality and 52% reduction in aortic calcification compared to the lowest quartile. MK-7 (90–180 µg/day) activates osteocalcin (bone matrix protein) and matrix Gla protein (MGP, which inhibits arterial calcification). MK-7 has superior half-life (3 days) vs MK-4 (hours). Caution with warfarin anticoagulation.' },
  { category: 'supplements', evidence_level: 'III', source: 'NIH ODS; Cochrane systematic reviews; NEJM', content: 'NAD+ precursors (NMN/NR): Nicotinamide mononucleotide (NMN) and nicotinamide riboside (NR) raise cellular NAD+ levels, which decline with age. Published RCTs (2021–2024, Level II–III): NMN 250–500 mg/day increases blood NAD+; small trials show improved muscle function, insulin sensitivity, and walking speed in older adults. Long-term safety > 12 months not yet established in large trials. Promising but not yet Level I evidence. Phase III trials ongoing.' },

  // DRUG INTERACTIONS (5)
  { category: 'drug_interactions', evidence_level: 'I', source: 'Natural Medicines Therapeutic Research Center; ARTG Australia; Cochrane', content: 'Anticoagulant interactions with supplements: Fish oil > 3 g/day, Vitamin E > 400 IU/day, CoQ10, and Ginkgo biloba each independently increase bleeding risk when combined with anticoagulants (warfarin, rivaroxaban, apixaban, dabigatran). Fish oil inhibits platelet aggregation via TXA2 reduction. Vitamin E inhibits platelet aggregation and Vitamin K-dependent coagulation factors. These combinations should be reviewed by a prescribing doctor. Supplement regimens must be disclosed to anticoagulant-prescribing clinicians.' },
  { category: 'drug_interactions', evidence_level: 'I', source: 'Natural Medicines Therapeutic Research Center; ARTG Australia; Cochrane', content: 'Levothyroxine absorption is reduced by concurrent mineral supplementation. Iron reduces thyroxine absorption by 30–40% via chelation in the gastrointestinal tract. Calcium carbonate, magnesium, and zinc have similar chelating effects. Biotin supplementation interferes with TSH immunoassay results (falsely lowers TSH, falsely elevates fT4) — stop biotin ≥ 72 hours before thyroid blood tests. Minimum separation between levothyroxine and mineral supplements: 2 hours.' },
  { category: 'drug_interactions', evidence_level: 'I', source: 'Natural Medicines Therapeutic Research Center; ARTG Australia; Cochrane', content: "St John's Wort (Hypericum perforatum) is a potent inducer of CYP3A4 (metabolic enzyme) and P-glycoprotein (drug efflux pump). Clinical consequences: reduces plasma concentrations of oral contraceptives (breakthrough bleeding, contraceptive failure), SSRIs/SNRIs (reduced efficacy; potential serotonin syndrome), warfarin (reduced anticoagulation, INR drop, thromboembolism risk), digoxin, HIV antiretrovirals, cyclosporin (organ rejection risk), and statins. ABSOLUTE CONTRAINDICATION with antidepressants, OCP, warfarin, and immunosuppressants." },
  { category: 'drug_interactions', evidence_level: 'I', source: 'Natural Medicines Therapeutic Research Center; ARTG Australia; Cochrane', content: 'Calcium and iron compete for absorption via the divalent metal transporter-1 (DMT1) in the duodenum. Calcium (≥ 300 mg) co-administered with iron reduces non-haem iron absorption by 30–60%. This interaction is clinically significant in iron-deficiency anaemia management. Recommendation: take iron ≥ 2 hours apart from calcium supplements or dairy-rich meals.' },
  { category: 'drug_interactions', evidence_level: 'I', source: 'Natural Medicines Therapeutic Research Center; ARTG Australia; Cochrane', content: 'Vitamin E (alpha-tocopherol) > 400 IU/day has antiplatelet effects and may increase bleeding risk, particularly in the perioperative period or when combined with anticoagulants or antiplatelet drugs (aspirin, clopidogrel). The HOPE-TOO trial (2005) found that long-term Vitamin E supplementation (400 IU/day) increased risk of heart failure in high-risk patients. Advise discontinuation ≥ 7 days before elective surgery.' },
];

// ---------------------------------------------------------------------------
// Embed via OpenRouter
// ---------------------------------------------------------------------------

async function embedBatch(texts: string[]): Promise<number[][]> {
  const res = await fetch('https://openrouter.ai/api/v1/embeddings', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${OPENROUTER_API_KEY}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({ model: 'perplexity/pplx-embed-v1-4b', input: texts }),
  });

  if (!res.ok) {
    const text = await res.text();
    throw new Error(`OpenRouter API error ${res.status}: ${text}`);
  }

  const json = await res.json() as { data: Array<{ embedding: number[] }> };
  return json.data.map((d) => d.embedding);
}

function escapeSql(s: string): string {
  return s.replace(/'/g, "''");
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main() {
  // Generate embeddings in batches of 20
  const BATCH = 20;
  const allEmbeddings: number[][] = [];

  for (let i = 0; i < RECORDS.length; i += BATCH) {
    const slice = RECORDS.slice(i, i + BATCH);
    console.log(`Embedding records ${i + 1}–${Math.min(i + BATCH, RECORDS.length)} of ${RECORDS.length}...`);
    const vecs = await embedBatch(slice.map((r) => r.content));
    allEmbeddings.push(...vecs);
  }

  console.log(`Generated ${allEmbeddings.length} embeddings. Writing SQL...`);

  // Build idempotent SQL — truncate then insert
  const insertStatements = RECORDS.map((r, i) => {
    const vec = `[${allEmbeddings[i]!.join(',')}]`;
    const meta = JSON.stringify({ source: r.source, category: r.category, evidence_level: r.evidence_level, published_at: '2024' });
    return `  ('${escapeSql(r.content)}', '${vec}', '${escapeSql(meta)}'::jsonb)`;
  }).join(',\n');

  const sql = `-- Auto-generated by scripts/seed-health-knowledge.ts
-- Clears and re-seeds agents.health_knowledge with proper 2560-dim embeddings.

DELETE FROM agents.health_knowledge;

INSERT INTO agents.health_knowledge (content, embedding, metadata) VALUES
${insertStatements};

SELECT COUNT(*) AS seeded_rows FROM agents.health_knowledge;
`;

  const sqlPath = join(process.cwd(), 'scripts', '_seed-health-knowledge.sql');
  writeFileSync(sqlPath, sql, 'utf8');
  console.log(`SQL written to ${sqlPath}.`);

  const dbPassword = process.env.SUPABASE_DB_PASSWORD;
  const projectId = 'raomphjkuypigdhytbzn';
  const dbUrl = dbPassword
    ? `postgresql://postgres:${dbPassword}@db.${projectId}.supabase.co:5432/postgres`
    : null;

  if (dbUrl) {
    try {
      console.log('Applying via psql...');
      execSync(`psql "${dbUrl}" -f "${sqlPath}"`, { stdio: 'inherit' });
      console.log('Done.');
      unlinkSync(sqlPath);
    } catch (err) {
      console.error('psql failed. SQL file retained at:', sqlPath);
      console.error('Run manually: psql "<DB_URL>" -f scripts/_seed-health-knowledge.sql');
      throw err;
    }
  } else {
    console.log('');
    console.log('No SUPABASE_DB_PASSWORD in env — SQL file retained.');
    console.log('Apply it via the Supabase dashboard SQL editor, or run:');
    console.log(`  SUPABASE_DB_PASSWORD=<pw> npx tsx --env-file=.env scripts/seed-health-knowledge.ts`);
    console.log('');
    console.log('SQL file path:', sqlPath);
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
